# Generated by Django 3.2.10 on 2022-01-16 13:55

from django.contrib.auth.models import Group
from django.db import migrations


def create_groups(*args):
    Group.objects.bulk_create([
        Group(name='Руководитель'),
        Group(name='Менеджер'),
        Group(name='Замерщик'),
        Group(name='Доставщик'),
        Group(name='Установщик'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211225_2137'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
